### PR TITLE
Fix flushInternal not succeeding

### PR DESCRIPTION
**Pull request by leyanlo**
This was broken in #158. Calling `this.flushInternal()` within a `setInterval()` fails because `this` does is not bound properly like it is for `this.flush()`. The result is that logging is never flushed, and we see a continuous stream of error messages every 5 seconds:

```
2019-01-23T23:58:59.012Z - error: Cannot read property 'getAndClear' of undefined message=Cannot read property 'getAndClear' of undefined, line=null, col=null, stack=TypeError: Cannot read property 'getAndClear' of undefined
    at flushInternal (http://localhost:3000/shipper/_static/client-vendor.js:37174:32), message=Cannot read property 'getAndClear' of undefined, captureType=browser, captureSource=client, framework=fusion
```

Verified that running the plugin with these changes properly flushes, including flushing before termination.

### CODE REVIEW

**Comment by KevinGrandon** [comment]
(We should see if we can write a test case to address this, maybe doesn't block landing though)

**Comment by leyanlo** [comment]
Added a test case for setInterval, and changed all UniversalEmitter methods to arrow functions for consistency

**Comment by KevinGrandon** [comment]
Relevant PR: https://github.com/fusionjs/fusion-plugin-universal-events/pull/177

**Comment by leyanlo** [comment]
Ah no worries, thanks for the update!

**Pull request closed without merging**
